stages:
  - build
  - deploy

maven-build:
  image: maven:3-jdk-8
  stage: build
  script:
    - mvn clean install


deploy:
  stage: deploy
  image: ruby:latest
  script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=$HEROKU_APP_NAME --api-key=$HEROKU_API_KEY
  only:
    - dev
